### ISSUE TITLE
Some problems aboout search_for_layer

### ISSUE THREAD

**Issue by Trent-tangtao** [microsoft/AutoML#17]
Thanks for your excellent work!
I am confused by the code of _search_structure_supernet.py/search_for_layer_
how to understand :
    order = [2, 3, 4, 1, 0, 2, 3, 4, 1, 0]
    limits = [3, 3, 3, 2, 2, 4, 4, 4, 4, 4]

**Comment by Z7zuqer** [comment]
Hi,

For reducing the search space, we need an order to reduce the search space in turn, so this is our rough definition order, not the best solution, and there may be better methods. We are looking forward to automatically sorting the importance of each layer of the network in future work.

Best,
Hao.
