### ISSUE TITLE
Some questions about experiments in the search phase

### ISSUE THREAD

**Issue by Sunrisulfr** [microsoft/AutoML#18]
Thanks for your excellent work!
Q1: I am confused by the configure file: ./experiments/configs/train/train.yaml
how to understand :
  PRE_PROB: (0.05,0.2,0.05,0.5,0.05,0.15)
Where do these numbers come from?

Q2: In  lib/core/train.py file, ‘random_cand’ represents the randomly searched path. What I want to ask is what number is used to represent the SkipConnect?
Related code:

Lib/core/train.py:        
        random_cand = prioritized_board.get_cand_with_prob(prob)
        random_cand.insert(0, [0])
        random_cand.append([0])
——————————————————
Lib/models/PrioritizedBoard.py:
    def get_cand_with_prob(self, prob=None):
        if prob is None:
            get_random_cand = [
                np.random.choice(
                    self.choice_num,
                    item).tolist() for item in self.sta_num]
        else:
            get_random_cand = [
                np.random.choice(
                    self.choice_num,
                    item,
                    prob).tolist() for item in self.sta_num]
         return get_random_cand
——————————————————
If a number is used to represent SkipConnect, why is choice_num set to 6?

I'm sorry that I didn't understand these two parts by myself, and I look forward to the author's answer.

**Comment by Z7zuqer** [comment]
Hi,

Q1: In addition to uniform sampling, we provide this kind of probabilistic sampling as a reference to inspire follow-up work. We hope that the high-performance sub-networks can bring some reference to network sampling. For example, there may be certain operations that appear frequently in many high-performance sub-models.

Q2: Our algorithm separates the skip-connect operation from other operations in the implementation process. In the definition of supernet, by adding skip-connect to each layer, the overall network depth changes with demand (for example, the 20-layer network is reduced to 7 layers), so our search space as a whole is skip-connect plus the rest 6 operations(MBconv), so in the *get_random_cand* step, only the remaining 6 operations will be randomly sampled.

Best,
Hao.

**Comment by Sunrisulfr** [comment]
Thanks for your response.
How can I search for several subnets of different depths (different numbers of skip-connect)? The depth of the paths in the prioritizedboard seems to be the same.
This is the information in the log file:
02/08 02:20:03 AM | No.0 (tensor(50.3906, device='cuda:0'), tensor(50.3906, device='cuda:0'), 372.74939199999994, [[0], [1, 0, 2, 0], [1, 2, 2, 2], [5, 1, 5, 3], [4, 4, 2, 2], [4, 4, 2, 3], [0]])
02/08 02:20:03 AM | No.1 (tensor(47.2656, device='cuda:0'), tensor(47.2656, device='cuda:0'), 464.00270400000005, [[0], [5, 1, 1, 5], [2, 2, 4, 5], [0, 1, 4, 1], [1, 5, 5, 5], [4, 3, 3, 2], [0]])
02/08 02:20:03 AM | No.2 (tensor(47.2656, device='cuda:0'), tensor(47.2656, device='cuda:0'), 383.0449599999999, [[0], [3, 3, 0, 0], [0, 5, 1, 2], [3, 2, 1, 3], [2, 0, 2, 2], [4, 2, 2, 1], [0]])
02/08 02:20:03 AM | No.3 (tensor(46.8750, device='cuda:0'), tensor(46.8750, device='cuda:0'), 378.78153599999996, [[0], [3, 0, 1, 0], [2, 5, 0, 2], [3, 0, 0, 4], [2, 5, 2, 0], [4, 3, 0, 1], [0]])
