### ISSUE TITLE
论文附录A中的backbone table有误？

### ISSUE THREAD

**Issue by nbl97** [microsoft/AutoML#19]
附录A中的backbone与附录B的图不对应，某些地方的stride和input shape应该是写错了，烦请看下。此外，pooling 前面的一个 1x1 conv 是普通的卷积吗，代码中思路并不是这么写的。

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project! Well received your opinions, we will further check the contents in the appendix to make sure whether there exist some mistakes. 

Best,
Hao.

**Comment by Z7zuqer** [comment]
Hi,

Models with different flops are different from each other. You could refer to https://github.com/microsoft/Cream/blob/main/lib/models/structures/childnet.py for more reference. And from https://github.com/microsoft/Cream/blob/e0de68affb0827b2a0108e7afa633dbc97b233f0/lib/models/structures/childnet.py#L55 you could see it's a 1x1 convolution.

Best,
Hao.
