### ISSUE TITLE
请问val数据集是自己划分的还是默认的？

### ISSUE THREAD

**Issue by nbl97** [microsoft/AutoML#20]
请问./data/imagenet/val 下的验证集是最终汇报精度使用的 5 万张的验证集吗？那论文中提到的 2048 张图片的验证集用于快速验证精度，在哪里体现？

**Comment by Z7zuqer** [comment]
Hi,

Q1: Yes, same as other papers.

Q2: https://github.com/microsoft/Cream/blob/7128b059da3b4c5ffd81799c0c0022fcb9bc83af/lib/utils/util.py#L18

Best,
Hao.

**Comment by HUALIMUGU** [comment]
Hi, thanks for your contributions, but I have a same question that the function you mentioned above seems not be used in the whole project under the Pycharm view, I would be appreciated if you can show me the usage.

Best wishes,
hualimugu.
