### ISSUE TITLE
DS block in appendix is incorrect?

### ISSUE THREAD

**Issue by luminolx** [microsoft/AutoML#31]
In appendix B and C, DS blocks used expansion rate as 4 and DepthwiseSeparableConv in timm.models.efficientnet_blocks was used in your code. However, in the original implementation of timm, DepthwiseSeparableConv has no parameters named expansion rate or something. Is that correct?

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project!

In [this line](https://github.com/microsoft/AutoML/blob/c868f5511f5ab0996e7530170833f9709b9dc9ec/Cream/lib/models/blocks/inverted_residual_block.py#L21), ` mid_chs = make_divisible(in_chs * exp_ratio)` indicates the expansion ratio. (also included in TIMM)

Best,

Hao.

**Comment by luminolx** [comment]
Thanks for your reply. 

I mean, DS blocks in appendix B and C have their names "DS" but you replied according to the implementations of "MB". And the true DepthwiseSeparableConv in timm.models.efficientnet_blocks has no expansion rate.

Do the "DS" and the "MB" have same structure in your paper? 

Thanks.

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project!

Yes, 'DS' and 'MB' are the same thing. They both indicate the inverted residual block which is proposed in MobileNet.

Best,
Hao.

**Comment by Z7zuqer** [comment]
Hi,

We're closing this issue, if you have any questions, please feel free to re-open it.

Best,

Hao.
