### ISSUE TITLE
question about resuming

### ISSUE THREAD

**Issue by zhiheng-ldj** [microsoft/AutoML#32]
Hi,

Thanks for your help and your great NAS idea!

I have a question about resuming training:

If I want to resume from a checkpoint, from my standpoint, I need 10 best checkpoints + meta-network checkpoint and model checkpoint. However, I don't find any code related to resume prioritized board and meta-network.

How do you deal with it?

Thanks!

**Comment by zhiheng-ldj** [comment]
Besides, could you help me with this? It seems something goes wrong when sorting the board?

```
File "/home/admin/cream/tools/../lib/models/PrioritizedBoard.py", line 130, in update_prioritized_board
self.prioritized_board = sorted(self.prioritized_board, reverse=True)
RuntimeError: bool value of Tensor with more than one value is ambiguous
```

Thanks!!

**Comment by Z7zuqer** [comment]
Hi,

Thanks for your interest in our project!

1) For supernet resuming, You could refer to [this line](https://github.com/microsoft/AutoML/blob/c868f5511f5ab0996e7530170833f9709b9dc9ec/Cream/tools/train.py#L203) to fetch more information about resuming. For subnet resuming, you could refer to [this line](https://github.com/microsoft/AutoML/blob/c868f5511f5ab0996e7530170833f9709b9dc9ec/Cream/tools/retrain.py#L143).

2) It seems you're sorting an array of boolean items. You should check whether each procedure is right.

Best,

Hao.

**Comment by Z7zuqer** [comment]
Hi,

We're closing this issue, if you have any questions, please feel free to re-open it.

Best,

Hao.
