### ISSUE TITLE
Does `embed dim` vary across Transformer blocks?

### ISSUE THREAD

**Issue by ParadoxZW** [microsoft/AutoML#33]
I was confused with this question when I read the paper of AutoFormer. According to the gif file in the README.md, the `embed dim` parameter does vary across blocks. So how do you deal with the shortcut when the input embed dim is different with the output embed dim for a Transformer block? And how do you deal with the dimension mismatch between one block's output embed and next one's input embed?

**Comment by silent-chen** [comment]
Hi,

Thanks for your interest. The embed dim does not change across blocks. We will update the gif to make it clearer soon.
