### ISSUE TITLE
About Appendix A in "AutoFormer: Searching Transformers for Visual Recognition"

### ISSUE THREAD

**Issue by NickChang97** [microsoft/AutoML#49]
Hi, I am very interested in your excellent work "AutoFormer: Searching Transformers for Visual Recognition". In this paper, you mentioned the Appendix A in section 3.3.  Did you release it? How can I get this Appendix A ?. Thanks in advance.

**Comment by silent-chen** [comment]
Hi,
Thanks for your interest. We will update the Arxiv version soon, which will include Appendix A.

**Comment by NickChang97** [comment]
Get it. Thanks for your reply
